/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import com.tokogae.data.event.model.SymptomPeriod;
import com.tokogae.data.event.service.SymptomPeriodService;
import com.tokogae.data.event.service.persistence.SymptomPeriodPersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the symptom period remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tokogae.data.event.service.impl.SymptomPeriodServiceImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see com.tokogae.data.event.service.impl.SymptomPeriodServiceImpl
 * @generated
 */
public abstract class SymptomPeriodServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, SymptomPeriodService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SymptomPeriodService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.tokogae.data.event.service.SymptomPeriodServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SymptomPeriodService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		symptomPeriodService = (SymptomPeriodService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SymptomPeriodService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SymptomPeriod.class;
	}

	protected String getModelClassName() {
		return SymptomPeriod.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = symptomPeriodPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected com.tokogae.data.event.service.SymptomPeriodLocalService
		symptomPeriodLocalService;

	protected SymptomPeriodService symptomPeriodService;

	@Reference
	protected SymptomPeriodPersistence symptomPeriodPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SymptomPeriodServiceBaseImpl.class);

}