buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "11.0.5"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.root.defaults.plugin"
apply plugin: 'java-library'

dependencies {
	implementation project(":util:source-formatter")
}

task formatSourceCustom(type: JavaExec)

formatSourceCustom {
	dependsOn(":util:source-formatter:compileJava")

	mainClass = 'com.tokogae.source.formatter.SourceFormatter'
	classpath = sourceSets.main.runtimeClasspath
}