##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=

##
## Java Parser
##

    java.parser.enabled=true

##
## Git
##

    git.liferay.portal.branch=master

##
##  CheckStyle Properties
##

    checkstyle.ExceptionPrintStackTraceCheck.enabled=false

    checkstyle.JSONUtilCheck.enabled=false

    checkstyle.ListUtilCheck.enabled=false

    checkstyle.StaticBlockCheck.enabled=false

    checkstyle.VariableDeclarationAsUsedCheck.enabled=false

##
## Source Check Properties
##

    source.check.BNDBundleInformationCheck.enabled=false

    source.check.BNDSuiteCheck.enabled=false

    source.check.CopyrightCheck.enabled=false

    source.check.GradleDependencyVersionCheck.enabled=false

    source.check.GradleTestDependencyVersionCheck.enabled=false

    source.check.JavaAnonymousInnerClassCheck.enabled=false

    source.check.JavaComponentAnnotationsCheck.enabled=false

    source.check.JavaDeprecatedKernelClassesCheck.enabled=false

    source.check.JavaInternalPackageCheck.enabled=false

    source.check.PropertiesLanguageKeysCheck.enabled=false

    source.check.StringMethodsCheck.enabled=false