/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PhraseUsage service. Represents a row in the &quot;TOKOGAEData_PhraseUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.model.impl.PhraseUsageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.model.impl.PhraseUsageImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see PhraseUsage
 * @generated
 */
@ProviderType
public interface PhraseUsageModel
	extends AttachedModel, BaseModel<PhraseUsage>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phrase usage model instance should use the {@link PhraseUsage} interface instead.
	 */

	/**
	 * Returns the primary key of this phrase usage.
	 *
	 * @return the primary key of this phrase usage
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phrase usage.
	 *
	 * @param primaryKey the primary key of this phrase usage
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this phrase usage.
	 *
	 * @return the mvcc version of this phrase usage
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this phrase usage.
	 *
	 * @param mvccVersion the mvcc version of this phrase usage
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the phrase usage ID of this phrase usage.
	 *
	 * @return the phrase usage ID of this phrase usage
	 */
	public long getPhraseUsageId();

	/**
	 * Sets the phrase usage ID of this phrase usage.
	 *
	 * @param phraseUsageId the phrase usage ID of this phrase usage
	 */
	public void setPhraseUsageId(long phraseUsageId);

	/**
	 * Returns the company ID of this phrase usage.
	 *
	 * @return the company ID of this phrase usage
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phrase usage.
	 *
	 * @param companyId the company ID of this phrase usage
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this phrase usage.
	 *
	 * @return the user ID of this phrase usage
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this phrase usage.
	 *
	 * @param userId the user ID of this phrase usage
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phrase usage.
	 *
	 * @return the user uuid of this phrase usage
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this phrase usage.
	 *
	 * @param userUuid the user uuid of this phrase usage
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this phrase usage.
	 *
	 * @return the create date of this phrase usage
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this phrase usage.
	 *
	 * @param createDate the create date of this phrase usage
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the phrase ID of this phrase usage.
	 *
	 * @return the phrase ID of this phrase usage
	 */
	public long getPhraseId();

	/**
	 * Sets the phrase ID of this phrase usage.
	 *
	 * @param phraseId the phrase ID of this phrase usage
	 */
	public void setPhraseId(long phraseId);

	/**
	 * Returns the fully qualified class name of this phrase usage.
	 *
	 * @return the fully qualified class name of this phrase usage
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this phrase usage.
	 *
	 * @return the class name ID of this phrase usage
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this phrase usage.
	 *
	 * @param classNameId the class name ID of this phrase usage
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this phrase usage.
	 *
	 * @return the class pk of this phrase usage
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this phrase usage.
	 *
	 * @param classPK the class pk of this phrase usage
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the attributes hash code of this phrase usage.
	 *
	 * @return the attributes hash code of this phrase usage
	 */
	public int getAttributesHashCode();

	/**
	 * Sets the attributes hash code of this phrase usage.
	 *
	 * @param attributesHashCode the attributes hash code of this phrase usage
	 */
	public void setAttributesHashCode(int attributesHashCode);

	@Override
	public PhraseUsage cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}