/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Phrase service. Represents a row in the &quot;TOKOGAEData_Phrase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.model.impl.PhraseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.model.impl.PhraseImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see Phrase
 * @generated
 */
@ProviderType
public interface PhraseModel
	extends BaseModel<Phrase>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phrase model instance should use the {@link Phrase} interface instead.
	 */

	/**
	 * Returns the primary key of this phrase.
	 *
	 * @return the primary key of this phrase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phrase.
	 *
	 * @param primaryKey the primary key of this phrase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this phrase.
	 *
	 * @return the mvcc version of this phrase
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this phrase.
	 *
	 * @param mvccVersion the mvcc version of this phrase
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the phrase ID of this phrase.
	 *
	 * @return the phrase ID of this phrase
	 */
	public long getPhraseId();

	/**
	 * Sets the phrase ID of this phrase.
	 *
	 * @param phraseId the phrase ID of this phrase
	 */
	public void setPhraseId(long phraseId);

	/**
	 * Returns the company ID of this phrase.
	 *
	 * @return the company ID of this phrase
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phrase.
	 *
	 * @param companyId the company ID of this phrase
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the text of this phrase.
	 *
	 * @return the text of this phrase
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this phrase.
	 *
	 * @param text the text of this phrase
	 */
	public void setText(String text);

	@Override
	public Phrase cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}