/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.event.model.Exercise;
import com.tokogae.data.event.model.ExerciseModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Exercise service. Represents a row in the &quot;Exercise&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExerciseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExerciseImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see ExerciseImpl
 * @generated
 */
@JSON(strict = true)
public class ExerciseModelImpl
	extends BaseModelImpl<Exercise> implements ExerciseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a exercise model instance should use the <code>Exercise</code> interface instead.
	 */
	public static final String TABLE_NAME = "Exercise";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"exerciseId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"occurDay", Types.BIGINT},
		{"occurDaySegment", Types.INTEGER}, {"occurTime", Types.BIGINT},
		{"name", Types.VARCHAR}, {"type_", Types.INTEGER},
		{"duration", Types.INTEGER}, {"intensityLevel", Types.INTEGER},
		{"quantity", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("exerciseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("occurDay", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("occurDaySegment", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("occurTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("duration", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("intensityLevel", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Exercise (mvccVersion LONG default 0 not null,exerciseId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,occurDay LONG,occurDaySegment INTEGER,occurTime LONG,name VARCHAR(75) null,type_ INTEGER,duration INTEGER,intensityLevel INTEGER,quantity INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Exercise";

	public static final String ORDER_BY_JPQL =
		" ORDER BY exercise.exerciseId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Exercise.exerciseId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXERCISEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ExerciseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _exerciseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExerciseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _exerciseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Exercise.class;
	}

	@Override
	public String getModelClassName() {
		return Exercise.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Exercise, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Exercise, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Exercise, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Exercise)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Exercise, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Exercise, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Exercise)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Exercise, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Exercise, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Exercise, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Exercise, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Exercise, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", Exercise::getMvccVersion);
			attributeGetterFunctions.put("exerciseId", Exercise::getExerciseId);
			attributeGetterFunctions.put("companyId", Exercise::getCompanyId);
			attributeGetterFunctions.put("userId", Exercise::getUserId);
			attributeGetterFunctions.put("createDate", Exercise::getCreateDate);
			attributeGetterFunctions.put("occurDay", Exercise::getOccurDay);
			attributeGetterFunctions.put(
				"occurDaySegment", Exercise::getOccurDaySegment);
			attributeGetterFunctions.put("occurTime", Exercise::getOccurTime);
			attributeGetterFunctions.put("name", Exercise::getName);
			attributeGetterFunctions.put("type", Exercise::getType);
			attributeGetterFunctions.put("duration", Exercise::getDuration);
			attributeGetterFunctions.put(
				"intensityLevel", Exercise::getIntensityLevel);
			attributeGetterFunctions.put("quantity", Exercise::getQuantity);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Exercise, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Exercise, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Exercise, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<Exercise, Long>)Exercise::setMvccVersion);
			attributeSetterBiConsumers.put(
				"exerciseId",
				(BiConsumer<Exercise, Long>)Exercise::setExerciseId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Exercise, Long>)Exercise::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Exercise, Long>)Exercise::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Exercise, Date>)Exercise::setCreateDate);
			attributeSetterBiConsumers.put(
				"occurDay", (BiConsumer<Exercise, Long>)Exercise::setOccurDay);
			attributeSetterBiConsumers.put(
				"occurDaySegment",
				(BiConsumer<Exercise, Integer>)Exercise::setOccurDaySegment);
			attributeSetterBiConsumers.put(
				"occurTime",
				(BiConsumer<Exercise, Long>)Exercise::setOccurTime);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Exercise, String>)Exercise::setName);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<Exercise, Integer>)Exercise::setType);
			attributeSetterBiConsumers.put(
				"duration",
				(BiConsumer<Exercise, Integer>)Exercise::setDuration);
			attributeSetterBiConsumers.put(
				"intensityLevel",
				(BiConsumer<Exercise, Integer>)Exercise::setIntensityLevel);
			attributeSetterBiConsumers.put(
				"quantity",
				(BiConsumer<Exercise, Integer>)Exercise::setQuantity);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getExerciseId() {
		return _exerciseId;
	}

	@Override
	public void setExerciseId(long exerciseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exerciseId = exerciseId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getOccurDay() {
		return _occurDay;
	}

	@Override
	public void setOccurDay(long occurDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDay = occurDay;
	}

	@JSON
	@Override
	public int getOccurDaySegment() {
		return _occurDaySegment;
	}

	@Override
	public void setOccurDaySegment(int occurDaySegment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDaySegment = occurDaySegment;
	}

	@JSON
	@Override
	public long getOccurTime() {
		return _occurTime;
	}

	@Override
	public void setOccurTime(long occurTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurTime = occurTime;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@JSON
	@Override
	public int getDuration() {
		return _duration;
	}

	@Override
	public void setDuration(int duration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_duration = duration;
	}

	@JSON
	@Override
	public int getIntensityLevel() {
		return _intensityLevel;
	}

	@Override
	public void setIntensityLevel(int intensityLevel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_intensityLevel = intensityLevel;
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantity = quantity;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Exercise.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Exercise toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Exercise>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExerciseImpl exerciseImpl = new ExerciseImpl();

		exerciseImpl.setMvccVersion(getMvccVersion());
		exerciseImpl.setExerciseId(getExerciseId());
		exerciseImpl.setCompanyId(getCompanyId());
		exerciseImpl.setUserId(getUserId());
		exerciseImpl.setCreateDate(getCreateDate());
		exerciseImpl.setOccurDay(getOccurDay());
		exerciseImpl.setOccurDaySegment(getOccurDaySegment());
		exerciseImpl.setOccurTime(getOccurTime());
		exerciseImpl.setName(getName());
		exerciseImpl.setType(getType());
		exerciseImpl.setDuration(getDuration());
		exerciseImpl.setIntensityLevel(getIntensityLevel());
		exerciseImpl.setQuantity(getQuantity());

		exerciseImpl.resetOriginalValues();

		return exerciseImpl;
	}

	@Override
	public Exercise cloneWithOriginalValues() {
		ExerciseImpl exerciseImpl = new ExerciseImpl();

		exerciseImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		exerciseImpl.setExerciseId(
			this.<Long>getColumnOriginalValue("exerciseId"));
		exerciseImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		exerciseImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		exerciseImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		exerciseImpl.setOccurDay(this.<Long>getColumnOriginalValue("occurDay"));
		exerciseImpl.setOccurDaySegment(
			this.<Integer>getColumnOriginalValue("occurDaySegment"));
		exerciseImpl.setOccurTime(
			this.<Long>getColumnOriginalValue("occurTime"));
		exerciseImpl.setName(this.<String>getColumnOriginalValue("name"));
		exerciseImpl.setType(this.<Integer>getColumnOriginalValue("type_"));
		exerciseImpl.setDuration(
			this.<Integer>getColumnOriginalValue("duration"));
		exerciseImpl.setIntensityLevel(
			this.<Integer>getColumnOriginalValue("intensityLevel"));
		exerciseImpl.setQuantity(
			this.<Integer>getColumnOriginalValue("quantity"));

		return exerciseImpl;
	}

	@Override
	public int compareTo(Exercise exercise) {
		long primaryKey = exercise.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Exercise)) {
			return false;
		}

		Exercise exercise = (Exercise)object;

		long primaryKey = exercise.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Exercise> toCacheModel() {
		ExerciseCacheModel exerciseCacheModel = new ExerciseCacheModel();

		exerciseCacheModel.mvccVersion = getMvccVersion();

		exerciseCacheModel.exerciseId = getExerciseId();

		exerciseCacheModel.companyId = getCompanyId();

		exerciseCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			exerciseCacheModel.createDate = createDate.getTime();
		}
		else {
			exerciseCacheModel.createDate = Long.MIN_VALUE;
		}

		exerciseCacheModel.occurDay = getOccurDay();

		exerciseCacheModel.occurDaySegment = getOccurDaySegment();

		exerciseCacheModel.occurTime = getOccurTime();

		exerciseCacheModel.name = getName();

		String name = exerciseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			exerciseCacheModel.name = null;
		}

		exerciseCacheModel.type = getType();

		exerciseCacheModel.duration = getDuration();

		exerciseCacheModel.intensityLevel = getIntensityLevel();

		exerciseCacheModel.quantity = getQuantity();

		return exerciseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Exercise, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Exercise, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Exercise, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Exercise)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Exercise>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Exercise.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _exerciseId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private long _occurDay;
	private int _occurDaySegment;
	private long _occurTime;
	private String _name;
	private int _type;
	private int _duration;
	private int _intensityLevel;
	private int _quantity;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Exercise, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Exercise)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("exerciseId", _exerciseId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("occurDay", _occurDay);
		_columnOriginalValues.put("occurDaySegment", _occurDaySegment);
		_columnOriginalValues.put("occurTime", _occurTime);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("duration", _duration);
		_columnOriginalValues.put("intensityLevel", _intensityLevel);
		_columnOriginalValues.put("quantity", _quantity);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("exerciseId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("occurDay", 32L);

		columnBitmasks.put("occurDaySegment", 64L);

		columnBitmasks.put("occurTime", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("type_", 512L);

		columnBitmasks.put("duration", 1024L);

		columnBitmasks.put("intensityLevel", 2048L);

		columnBitmasks.put("quantity", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Exercise _escapedModel;

}