/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.tokogae.data.event.model.Exercise;
import com.tokogae.data.event.service.ExerciseLocalServiceUtil;

/**
 * The extended model base implementation for the Exercise service. Represents a row in the &quot;TOKOGAEData_Exercise&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExerciseImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see ExerciseImpl
 * @see Exercise
 * @generated
 */
public abstract class ExerciseBaseImpl
	extends ExerciseModelImpl implements Exercise {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a exercise model instance should use the <code>Exercise</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ExerciseLocalServiceUtil.addExercise(this);
		}
		else {
			ExerciseLocalServiceUtil.updateExercise(this);
		}
	}

}