/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.tokogae.data.event.model.FoodItem;
import com.tokogae.data.event.service.FoodItemLocalServiceUtil;

/**
 * The extended model base implementation for the FoodItem service. Represents a row in the &quot;TOKOGAEData_FoodItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FoodItemImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see FoodItemImpl
 * @see FoodItem
 * @generated
 */
public abstract class FoodItemBaseImpl
	extends FoodItemModelImpl implements FoodItem {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a food item model instance should use the <code>FoodItem</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FoodItemLocalServiceUtil.addFoodItem(this);
		}
		else {
			FoodItemLocalServiceUtil.updateFoodItem(this);
		}
	}

}