/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.event.model.FoodItem;
import com.tokogae.data.event.model.FoodItemModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FoodItem service. Represents a row in the &quot;FoodItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FoodItemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FoodItemImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see FoodItemImpl
 * @generated
 */
@JSON(strict = true)
public class FoodItemModelImpl
	extends BaseModelImpl<FoodItem> implements FoodItemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a food item model instance should use the <code>FoodItem</code> interface instead.
	 */
	public static final String TABLE_NAME = "FoodItem";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"foodItemId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"locationOfOrigin", Types.VARCHAR}, {"brand", Types.VARCHAR},
		{"quantity", Types.BIGINT}, {"quantityUnit", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("foodItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locationOfOrigin", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("brand", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantity", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantityUnit", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FoodItem (mvccVersion LONG default 0 not null,foodItemId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,name VARCHAR(75) null,locationOfOrigin VARCHAR(75) null,brand VARCHAR(75) null,quantity LONG,quantityUnit VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FoodItem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY foodItem.foodItemId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FoodItem.foodItemId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FOODITEMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FoodItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _foodItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFoodItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _foodItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FoodItem.class;
	}

	@Override
	public String getModelClassName() {
		return FoodItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FoodItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FoodItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FoodItem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((FoodItem)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FoodItem, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FoodItem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FoodItem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FoodItem, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FoodItem, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FoodItem, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FoodItem, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<FoodItem, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", FoodItem::getMvccVersion);
			attributeGetterFunctions.put("foodItemId", FoodItem::getFoodItemId);
			attributeGetterFunctions.put("companyId", FoodItem::getCompanyId);
			attributeGetterFunctions.put("userId", FoodItem::getUserId);
			attributeGetterFunctions.put("createDate", FoodItem::getCreateDate);
			attributeGetterFunctions.put("name", FoodItem::getName);
			attributeGetterFunctions.put(
				"locationOfOrigin", FoodItem::getLocationOfOrigin);
			attributeGetterFunctions.put("brand", FoodItem::getBrand);
			attributeGetterFunctions.put("quantity", FoodItem::getQuantity);
			attributeGetterFunctions.put(
				"quantityUnit", FoodItem::getQuantityUnit);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FoodItem, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FoodItem, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FoodItem, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<FoodItem, Long>)FoodItem::setMvccVersion);
			attributeSetterBiConsumers.put(
				"foodItemId",
				(BiConsumer<FoodItem, Long>)FoodItem::setFoodItemId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FoodItem, Long>)FoodItem::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<FoodItem, Long>)FoodItem::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FoodItem, Date>)FoodItem::setCreateDate);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<FoodItem, String>)FoodItem::setName);
			attributeSetterBiConsumers.put(
				"locationOfOrigin",
				(BiConsumer<FoodItem, String>)FoodItem::setLocationOfOrigin);
			attributeSetterBiConsumers.put(
				"brand", (BiConsumer<FoodItem, String>)FoodItem::setBrand);
			attributeSetterBiConsumers.put(
				"quantity", (BiConsumer<FoodItem, Long>)FoodItem::setQuantity);
			attributeSetterBiConsumers.put(
				"quantityUnit",
				(BiConsumer<FoodItem, String>)FoodItem::setQuantityUnit);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getFoodItemId() {
		return _foodItemId;
	}

	@Override
	public void setFoodItemId(long foodItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_foodItemId = foodItemId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getLocationOfOrigin() {
		if (_locationOfOrigin == null) {
			return "";
		}
		else {
			return _locationOfOrigin;
		}
	}

	@Override
	public void setLocationOfOrigin(String locationOfOrigin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationOfOrigin = locationOfOrigin;
	}

	@JSON
	@Override
	public String getBrand() {
		if (_brand == null) {
			return "";
		}
		else {
			return _brand;
		}
	}

	@Override
	public void setBrand(String brand) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brand = brand;
	}

	@JSON
	@Override
	public long getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(long quantity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantity = quantity;
	}

	@JSON
	@Override
	public String getQuantityUnit() {
		if (_quantityUnit == null) {
			return "";
		}
		else {
			return _quantityUnit;
		}
	}

	@Override
	public void setQuantityUnit(String quantityUnit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantityUnit = quantityUnit;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FoodItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FoodItem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FoodItem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FoodItemImpl foodItemImpl = new FoodItemImpl();

		foodItemImpl.setMvccVersion(getMvccVersion());
		foodItemImpl.setFoodItemId(getFoodItemId());
		foodItemImpl.setCompanyId(getCompanyId());
		foodItemImpl.setUserId(getUserId());
		foodItemImpl.setCreateDate(getCreateDate());
		foodItemImpl.setName(getName());
		foodItemImpl.setLocationOfOrigin(getLocationOfOrigin());
		foodItemImpl.setBrand(getBrand());
		foodItemImpl.setQuantity(getQuantity());
		foodItemImpl.setQuantityUnit(getQuantityUnit());

		foodItemImpl.resetOriginalValues();

		return foodItemImpl;
	}

	@Override
	public FoodItem cloneWithOriginalValues() {
		FoodItemImpl foodItemImpl = new FoodItemImpl();

		foodItemImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		foodItemImpl.setFoodItemId(
			this.<Long>getColumnOriginalValue("foodItemId"));
		foodItemImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		foodItemImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		foodItemImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		foodItemImpl.setName(this.<String>getColumnOriginalValue("name"));
		foodItemImpl.setLocationOfOrigin(
			this.<String>getColumnOriginalValue("locationOfOrigin"));
		foodItemImpl.setBrand(this.<String>getColumnOriginalValue("brand"));
		foodItemImpl.setQuantity(this.<Long>getColumnOriginalValue("quantity"));
		foodItemImpl.setQuantityUnit(
			this.<String>getColumnOriginalValue("quantityUnit"));

		return foodItemImpl;
	}

	@Override
	public int compareTo(FoodItem foodItem) {
		long primaryKey = foodItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FoodItem)) {
			return false;
		}

		FoodItem foodItem = (FoodItem)object;

		long primaryKey = foodItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FoodItem> toCacheModel() {
		FoodItemCacheModel foodItemCacheModel = new FoodItemCacheModel();

		foodItemCacheModel.mvccVersion = getMvccVersion();

		foodItemCacheModel.foodItemId = getFoodItemId();

		foodItemCacheModel.companyId = getCompanyId();

		foodItemCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			foodItemCacheModel.createDate = createDate.getTime();
		}
		else {
			foodItemCacheModel.createDate = Long.MIN_VALUE;
		}

		foodItemCacheModel.name = getName();

		String name = foodItemCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			foodItemCacheModel.name = null;
		}

		foodItemCacheModel.locationOfOrigin = getLocationOfOrigin();

		String locationOfOrigin = foodItemCacheModel.locationOfOrigin;

		if ((locationOfOrigin != null) && (locationOfOrigin.length() == 0)) {
			foodItemCacheModel.locationOfOrigin = null;
		}

		foodItemCacheModel.brand = getBrand();

		String brand = foodItemCacheModel.brand;

		if ((brand != null) && (brand.length() == 0)) {
			foodItemCacheModel.brand = null;
		}

		foodItemCacheModel.quantity = getQuantity();

		foodItemCacheModel.quantityUnit = getQuantityUnit();

		String quantityUnit = foodItemCacheModel.quantityUnit;

		if ((quantityUnit != null) && (quantityUnit.length() == 0)) {
			foodItemCacheModel.quantityUnit = null;
		}

		return foodItemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FoodItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FoodItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FoodItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FoodItem)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FoodItem>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FoodItem.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _foodItemId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private String _name;
	private String _locationOfOrigin;
	private String _brand;
	private long _quantity;
	private String _quantityUnit;

	public <T> T getColumnValue(String columnName) {
		Function<FoodItem, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FoodItem)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("foodItemId", _foodItemId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("locationOfOrigin", _locationOfOrigin);
		_columnOriginalValues.put("brand", _brand);
		_columnOriginalValues.put("quantity", _quantity);
		_columnOriginalValues.put("quantityUnit", _quantityUnit);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("foodItemId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("name", 32L);

		columnBitmasks.put("locationOfOrigin", 64L);

		columnBitmasks.put("brand", 128L);

		columnBitmasks.put("quantity", 256L);

		columnBitmasks.put("quantityUnit", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FoodItem _escapedModel;

}