/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.event.model.Sleep;
import com.tokogae.data.event.model.SleepModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Sleep service. Represents a row in the &quot;TOKOGAEData_Sleep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SleepModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SleepImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SleepImpl
 * @generated
 */
@JSON(strict = true)
public class SleepModelImpl extends BaseModelImpl<Sleep> implements SleepModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sleep model instance should use the <code>Sleep</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAEData_Sleep";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"sleepId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"subjectId", Types.BIGINT},
		{"occurDay", Types.BIGINT}, {"occurDaySegment", Types.INTEGER},
		{"occurTime", Types.BIGINT}, {"duration", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sleepId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("occurDay", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("occurDaySegment", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("occurTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("duration", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAEData_Sleep (mvccVersion LONG default 0 not null,sleepId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,subjectId LONG,occurDay LONG,occurDaySegment INTEGER,occurTime LONG,duration LONG)";

	public static final String TABLE_SQL_DROP = "drop table TOKOGAEData_Sleep";

	public static final String ORDER_BY_JPQL = " ORDER BY sleep.sleepId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAEData_Sleep.sleepId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SLEEPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SleepModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sleepId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSleepId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sleepId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Sleep.class;
	}

	@Override
	public String getModelClassName() {
		return Sleep.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Sleep, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Sleep, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sleep, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Sleep)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Sleep, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Sleep, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Sleep)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Sleep, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Sleep, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Sleep, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Sleep, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Sleep, Object>>();

			attributeGetterFunctions.put("mvccVersion", Sleep::getMvccVersion);
			attributeGetterFunctions.put("sleepId", Sleep::getSleepId);
			attributeGetterFunctions.put("companyId", Sleep::getCompanyId);
			attributeGetterFunctions.put("userId", Sleep::getUserId);
			attributeGetterFunctions.put("createDate", Sleep::getCreateDate);
			attributeGetterFunctions.put("subjectId", Sleep::getSubjectId);
			attributeGetterFunctions.put("occurDay", Sleep::getOccurDay);
			attributeGetterFunctions.put(
				"occurDaySegment", Sleep::getOccurDaySegment);
			attributeGetterFunctions.put("occurTime", Sleep::getOccurTime);
			attributeGetterFunctions.put("duration", Sleep::getDuration);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Sleep, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Sleep, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Sleep, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion", (BiConsumer<Sleep, Long>)Sleep::setMvccVersion);
			attributeSetterBiConsumers.put(
				"sleepId", (BiConsumer<Sleep, Long>)Sleep::setSleepId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Sleep, Long>)Sleep::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Sleep, Long>)Sleep::setUserId);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Sleep, Date>)Sleep::setCreateDate);
			attributeSetterBiConsumers.put(
				"subjectId", (BiConsumer<Sleep, Long>)Sleep::setSubjectId);
			attributeSetterBiConsumers.put(
				"occurDay", (BiConsumer<Sleep, Long>)Sleep::setOccurDay);
			attributeSetterBiConsumers.put(
				"occurDaySegment",
				(BiConsumer<Sleep, Integer>)Sleep::setOccurDaySegment);
			attributeSetterBiConsumers.put(
				"occurTime", (BiConsumer<Sleep, Long>)Sleep::setOccurTime);
			attributeSetterBiConsumers.put(
				"duration", (BiConsumer<Sleep, Long>)Sleep::setDuration);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getSleepId() {
		return _sleepId;
	}

	@Override
	public void setSleepId(long sleepId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sleepId = sleepId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subjectId = subjectId;
	}

	@JSON
	@Override
	public long getOccurDay() {
		return _occurDay;
	}

	@Override
	public void setOccurDay(long occurDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDay = occurDay;
	}

	@JSON
	@Override
	public int getOccurDaySegment() {
		return _occurDaySegment;
	}

	@Override
	public void setOccurDaySegment(int occurDaySegment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDaySegment = occurDaySegment;
	}

	@JSON
	@Override
	public long getOccurTime() {
		return _occurTime;
	}

	@Override
	public void setOccurTime(long occurTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurTime = occurTime;
	}

	@JSON
	@Override
	public long getDuration() {
		return _duration;
	}

	@Override
	public void setDuration(long duration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_duration = duration;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Sleep.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sleep toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Sleep>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SleepImpl sleepImpl = new SleepImpl();

		sleepImpl.setMvccVersion(getMvccVersion());
		sleepImpl.setSleepId(getSleepId());
		sleepImpl.setCompanyId(getCompanyId());
		sleepImpl.setUserId(getUserId());
		sleepImpl.setCreateDate(getCreateDate());
		sleepImpl.setSubjectId(getSubjectId());
		sleepImpl.setOccurDay(getOccurDay());
		sleepImpl.setOccurDaySegment(getOccurDaySegment());
		sleepImpl.setOccurTime(getOccurTime());
		sleepImpl.setDuration(getDuration());

		sleepImpl.resetOriginalValues();

		return sleepImpl;
	}

	@Override
	public Sleep cloneWithOriginalValues() {
		SleepImpl sleepImpl = new SleepImpl();

		sleepImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		sleepImpl.setSleepId(this.<Long>getColumnOriginalValue("sleepId"));
		sleepImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		sleepImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		sleepImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		sleepImpl.setSubjectId(this.<Long>getColumnOriginalValue("subjectId"));
		sleepImpl.setOccurDay(this.<Long>getColumnOriginalValue("occurDay"));
		sleepImpl.setOccurDaySegment(
			this.<Integer>getColumnOriginalValue("occurDaySegment"));
		sleepImpl.setOccurTime(this.<Long>getColumnOriginalValue("occurTime"));
		sleepImpl.setDuration(this.<Long>getColumnOriginalValue("duration"));

		return sleepImpl;
	}

	@Override
	public int compareTo(Sleep sleep) {
		long primaryKey = sleep.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Sleep)) {
			return false;
		}

		Sleep sleep = (Sleep)object;

		long primaryKey = sleep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Sleep> toCacheModel() {
		SleepCacheModel sleepCacheModel = new SleepCacheModel();

		sleepCacheModel.mvccVersion = getMvccVersion();

		sleepCacheModel.sleepId = getSleepId();

		sleepCacheModel.companyId = getCompanyId();

		sleepCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			sleepCacheModel.createDate = createDate.getTime();
		}
		else {
			sleepCacheModel.createDate = Long.MIN_VALUE;
		}

		sleepCacheModel.subjectId = getSubjectId();

		sleepCacheModel.occurDay = getOccurDay();

		sleepCacheModel.occurDaySegment = getOccurDaySegment();

		sleepCacheModel.occurTime = getOccurTime();

		sleepCacheModel.duration = getDuration();

		return sleepCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Sleep, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Sleep, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sleep, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Sleep)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Sleep>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Sleep.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _sleepId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private long _subjectId;
	private long _occurDay;
	private int _occurDaySegment;
	private long _occurTime;
	private long _duration;

	public <T> T getColumnValue(String columnName) {
		Function<Sleep, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Sleep)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("sleepId", _sleepId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("subjectId", _subjectId);
		_columnOriginalValues.put("occurDay", _occurDay);
		_columnOriginalValues.put("occurDaySegment", _occurDaySegment);
		_columnOriginalValues.put("occurTime", _occurTime);
		_columnOriginalValues.put("duration", _duration);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("sleepId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("subjectId", 32L);

		columnBitmasks.put("occurDay", 64L);

		columnBitmasks.put("occurDaySegment", 128L);

		columnBitmasks.put("occurTime", 256L);

		columnBitmasks.put("duration", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Sleep _escapedModel;

}