/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.tokogae.data.event.model.Sleep;
import com.tokogae.data.event.service.SleepLocalServiceUtil;

/**
 * The extended model base implementation for the Sleep service. Represents a row in the &quot;TOKOGAEData_Sleep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SleepImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SleepImpl
 * @see Sleep
 * @generated
 */
public abstract class SleepBaseImpl extends SleepModelImpl implements Sleep {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sleep model instance should use the <code>Sleep</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SleepLocalServiceUtil.addSleep(this);
		}
		else {
			SleepLocalServiceUtil.updateSleep(this);
		}
	}

}