/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.event.model.Symptom;
import com.tokogae.data.event.model.SymptomModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Symptom service. Represents a row in the &quot;TOKOGAEData_Symptom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SymptomModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SymptomImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SymptomImpl
 * @generated
 */
@JSON(strict = true)
public class SymptomModelImpl
	extends BaseModelImpl<Symptom> implements SymptomModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a symptom model instance should use the <code>Symptom</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAEData_Symptom";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"symptomId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"subjectId", Types.BIGINT},
		{"occurDay", Types.BIGINT}, {"occurDaySegment", Types.INTEGER},
		{"occurTime", Types.BIGINT}, {"name", Types.VARCHAR},
		{"affectedArea", Types.VARCHAR}, {"extended", Types.BOOLEAN},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"intensityLevel", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("symptomId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("occurDay", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("occurDaySegment", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("occurTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("affectedArea", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("extended", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("intensityLevel", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAEData_Symptom (mvccVersion LONG default 0 not null,symptomId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,subjectId LONG,occurDay LONG,occurDaySegment INTEGER,occurTime LONG,name VARCHAR(75) null,affectedArea VARCHAR(75) null,extended BOOLEAN,startDate DATE null,endDate DATE null,intensityLevel INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table TOKOGAEData_Symptom";

	public static final String ORDER_BY_JPQL =
		" ORDER BY symptom.symptomId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAEData_Symptom.symptomId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SYMPTOMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SymptomModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _symptomId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSymptomId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _symptomId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Symptom.class;
	}

	@Override
	public String getModelClassName() {
		return Symptom.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Symptom, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Symptom, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Symptom, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Symptom)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Symptom, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Symptom, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Symptom)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Symptom, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Symptom, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Symptom, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Symptom, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Symptom, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", Symptom::getMvccVersion);
			attributeGetterFunctions.put("symptomId", Symptom::getSymptomId);
			attributeGetterFunctions.put("companyId", Symptom::getCompanyId);
			attributeGetterFunctions.put("userId", Symptom::getUserId);
			attributeGetterFunctions.put("createDate", Symptom::getCreateDate);
			attributeGetterFunctions.put("subjectId", Symptom::getSubjectId);
			attributeGetterFunctions.put("occurDay", Symptom::getOccurDay);
			attributeGetterFunctions.put(
				"occurDaySegment", Symptom::getOccurDaySegment);
			attributeGetterFunctions.put("occurTime", Symptom::getOccurTime);
			attributeGetterFunctions.put("name", Symptom::getName);
			attributeGetterFunctions.put(
				"affectedArea", Symptom::getAffectedArea);
			attributeGetterFunctions.put("extended", Symptom::getExtended);
			attributeGetterFunctions.put("startDate", Symptom::getStartDate);
			attributeGetterFunctions.put("endDate", Symptom::getEndDate);
			attributeGetterFunctions.put(
				"intensityLevel", Symptom::getIntensityLevel);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Symptom, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Symptom, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Symptom, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<Symptom, Long>)Symptom::setMvccVersion);
			attributeSetterBiConsumers.put(
				"symptomId", (BiConsumer<Symptom, Long>)Symptom::setSymptomId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Symptom, Long>)Symptom::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Symptom, Long>)Symptom::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Symptom, Date>)Symptom::setCreateDate);
			attributeSetterBiConsumers.put(
				"subjectId", (BiConsumer<Symptom, Long>)Symptom::setSubjectId);
			attributeSetterBiConsumers.put(
				"occurDay", (BiConsumer<Symptom, Long>)Symptom::setOccurDay);
			attributeSetterBiConsumers.put(
				"occurDaySegment",
				(BiConsumer<Symptom, Integer>)Symptom::setOccurDaySegment);
			attributeSetterBiConsumers.put(
				"occurTime", (BiConsumer<Symptom, Long>)Symptom::setOccurTime);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Symptom, String>)Symptom::setName);
			attributeSetterBiConsumers.put(
				"affectedArea",
				(BiConsumer<Symptom, String>)Symptom::setAffectedArea);
			attributeSetterBiConsumers.put(
				"extended", (BiConsumer<Symptom, Boolean>)Symptom::setExtended);
			attributeSetterBiConsumers.put(
				"startDate", (BiConsumer<Symptom, Date>)Symptom::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate", (BiConsumer<Symptom, Date>)Symptom::setEndDate);
			attributeSetterBiConsumers.put(
				"intensityLevel",
				(BiConsumer<Symptom, Integer>)Symptom::setIntensityLevel);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getSymptomId() {
		return _symptomId;
	}

	@Override
	public void setSymptomId(long symptomId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_symptomId = symptomId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subjectId = subjectId;
	}

	@JSON
	@Override
	public long getOccurDay() {
		return _occurDay;
	}

	@Override
	public void setOccurDay(long occurDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDay = occurDay;
	}

	@JSON
	@Override
	public int getOccurDaySegment() {
		return _occurDaySegment;
	}

	@Override
	public void setOccurDaySegment(int occurDaySegment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurDaySegment = occurDaySegment;
	}

	@JSON
	@Override
	public long getOccurTime() {
		return _occurTime;
	}

	@Override
	public void setOccurTime(long occurTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occurTime = occurTime;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getAffectedArea() {
		if (_affectedArea == null) {
			return "";
		}
		else {
			return _affectedArea;
		}
	}

	@Override
	public void setAffectedArea(String affectedArea) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_affectedArea = affectedArea;
	}

	@JSON
	@Override
	public boolean getExtended() {
		return _extended;
	}

	@JSON
	@Override
	public boolean isExtended() {
		return _extended;
	}

	@Override
	public void setExtended(boolean extended) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extended = extended;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public int getIntensityLevel() {
		return _intensityLevel;
	}

	@Override
	public void setIntensityLevel(int intensityLevel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_intensityLevel = intensityLevel;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Symptom.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Symptom toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Symptom>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SymptomImpl symptomImpl = new SymptomImpl();

		symptomImpl.setMvccVersion(getMvccVersion());
		symptomImpl.setSymptomId(getSymptomId());
		symptomImpl.setCompanyId(getCompanyId());
		symptomImpl.setUserId(getUserId());
		symptomImpl.setCreateDate(getCreateDate());
		symptomImpl.setSubjectId(getSubjectId());
		symptomImpl.setOccurDay(getOccurDay());
		symptomImpl.setOccurDaySegment(getOccurDaySegment());
		symptomImpl.setOccurTime(getOccurTime());
		symptomImpl.setName(getName());
		symptomImpl.setAffectedArea(getAffectedArea());
		symptomImpl.setExtended(isExtended());
		symptomImpl.setStartDate(getStartDate());
		symptomImpl.setEndDate(getEndDate());
		symptomImpl.setIntensityLevel(getIntensityLevel());

		symptomImpl.resetOriginalValues();

		return symptomImpl;
	}

	@Override
	public Symptom cloneWithOriginalValues() {
		SymptomImpl symptomImpl = new SymptomImpl();

		symptomImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		symptomImpl.setSymptomId(
			this.<Long>getColumnOriginalValue("symptomId"));
		symptomImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		symptomImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		symptomImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		symptomImpl.setSubjectId(
			this.<Long>getColumnOriginalValue("subjectId"));
		symptomImpl.setOccurDay(this.<Long>getColumnOriginalValue("occurDay"));
		symptomImpl.setOccurDaySegment(
			this.<Integer>getColumnOriginalValue("occurDaySegment"));
		symptomImpl.setOccurTime(
			this.<Long>getColumnOriginalValue("occurTime"));
		symptomImpl.setName(this.<String>getColumnOriginalValue("name"));
		symptomImpl.setAffectedArea(
			this.<String>getColumnOriginalValue("affectedArea"));
		symptomImpl.setExtended(
			this.<Boolean>getColumnOriginalValue("extended"));
		symptomImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		symptomImpl.setEndDate(this.<Date>getColumnOriginalValue("endDate"));
		symptomImpl.setIntensityLevel(
			this.<Integer>getColumnOriginalValue("intensityLevel"));

		return symptomImpl;
	}

	@Override
	public int compareTo(Symptom symptom) {
		long primaryKey = symptom.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Symptom)) {
			return false;
		}

		Symptom symptom = (Symptom)object;

		long primaryKey = symptom.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Symptom> toCacheModel() {
		SymptomCacheModel symptomCacheModel = new SymptomCacheModel();

		symptomCacheModel.mvccVersion = getMvccVersion();

		symptomCacheModel.symptomId = getSymptomId();

		symptomCacheModel.companyId = getCompanyId();

		symptomCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			symptomCacheModel.createDate = createDate.getTime();
		}
		else {
			symptomCacheModel.createDate = Long.MIN_VALUE;
		}

		symptomCacheModel.subjectId = getSubjectId();

		symptomCacheModel.occurDay = getOccurDay();

		symptomCacheModel.occurDaySegment = getOccurDaySegment();

		symptomCacheModel.occurTime = getOccurTime();

		symptomCacheModel.name = getName();

		String name = symptomCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			symptomCacheModel.name = null;
		}

		symptomCacheModel.affectedArea = getAffectedArea();

		String affectedArea = symptomCacheModel.affectedArea;

		if ((affectedArea != null) && (affectedArea.length() == 0)) {
			symptomCacheModel.affectedArea = null;
		}

		symptomCacheModel.extended = isExtended();

		Date startDate = getStartDate();

		if (startDate != null) {
			symptomCacheModel.startDate = startDate.getTime();
		}
		else {
			symptomCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			symptomCacheModel.endDate = endDate.getTime();
		}
		else {
			symptomCacheModel.endDate = Long.MIN_VALUE;
		}

		symptomCacheModel.intensityLevel = getIntensityLevel();

		return symptomCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Symptom, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Symptom, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Symptom, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Symptom)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Symptom>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Symptom.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _symptomId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private long _subjectId;
	private long _occurDay;
	private int _occurDaySegment;
	private long _occurTime;
	private String _name;
	private String _affectedArea;
	private boolean _extended;
	private Date _startDate;
	private Date _endDate;
	private int _intensityLevel;

	public <T> T getColumnValue(String columnName) {
		Function<Symptom, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Symptom)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("symptomId", _symptomId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("subjectId", _subjectId);
		_columnOriginalValues.put("occurDay", _occurDay);
		_columnOriginalValues.put("occurDaySegment", _occurDaySegment);
		_columnOriginalValues.put("occurTime", _occurTime);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("affectedArea", _affectedArea);
		_columnOriginalValues.put("extended", _extended);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("intensityLevel", _intensityLevel);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("symptomId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("subjectId", 32L);

		columnBitmasks.put("occurDay", 64L);

		columnBitmasks.put("occurDaySegment", 128L);

		columnBitmasks.put("occurTime", 256L);

		columnBitmasks.put("name", 512L);

		columnBitmasks.put("affectedArea", 1024L);

		columnBitmasks.put("extended", 2048L);

		columnBitmasks.put("startDate", 4096L);

		columnBitmasks.put("endDate", 8192L);

		columnBitmasks.put("intensityLevel", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Symptom _escapedModel;

}