/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.tokogae.data.event.model.SymptomPeriod;
import com.tokogae.data.event.service.SymptomPeriodLocalServiceUtil;

/**
 * The extended model base implementation for the SymptomPeriod service. Represents a row in the &quot;TOKOGAEData_SymptomPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SymptomPeriodImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SymptomPeriodImpl
 * @see SymptomPeriod
 * @generated
 */
public abstract class SymptomPeriodBaseImpl
	extends SymptomPeriodModelImpl implements SymptomPeriod {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a symptom period model instance should use the <code>SymptomPeriod</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SymptomPeriodLocalServiceUtil.addSymptomPeriod(this);
		}
		else {
			SymptomPeriodLocalServiceUtil.updateSymptomPeriod(this);
		}
	}

}