/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.tokogae.data.event.model.Symptom;
import com.tokogae.data.event.service.SymptomLocalServiceUtil;

/**
 * The extended model base implementation for the Symptom service. Represents a row in the &quot;Symptom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SymptomImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SymptomImpl
 * @see Symptom
 * @generated
 */
public abstract class SymptomBaseImpl
	extends SymptomModelImpl implements Symptom {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a symptom model instance should use the <code>Symptom</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SymptomLocalServiceUtil.addSymptom(this);
		}
		else {
			SymptomLocalServiceUtil.updateSymptom(this);
		}
	}

}