/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.event.model.SymptomPeriod;
import com.tokogae.data.event.model.SymptomPeriodModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SymptomPeriod service. Represents a row in the &quot;TOKOGAEData_SymptomPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SymptomPeriodModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SymptomPeriodImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SymptomPeriodImpl
 * @generated
 */
@JSON(strict = true)
public class SymptomPeriodModelImpl
	extends BaseModelImpl<SymptomPeriod> implements SymptomPeriodModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a symptom period model instance should use the <code>SymptomPeriod</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAEData_SymptomPeriod";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"symptomId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"subjectId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("symptomId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAEData_SymptomPeriod (mvccVersion LONG default 0 not null,symptomId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,subjectId LONG,name VARCHAR(75) null,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table TOKOGAEData_SymptomPeriod";

	public static final String ORDER_BY_JPQL =
		" ORDER BY symptomPeriod.symptomId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAEData_SymptomPeriod.symptomId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SYMPTOMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SymptomPeriodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _symptomId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSymptomId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _symptomId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SymptomPeriod.class;
	}

	@Override
	public String getModelClassName() {
		return SymptomPeriod.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SymptomPeriod, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SymptomPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SymptomPeriod, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SymptomPeriod)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SymptomPeriod, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SymptomPeriod, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SymptomPeriod)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SymptomPeriod, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SymptomPeriod, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SymptomPeriod, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SymptomPeriod, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<SymptomPeriod, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", SymptomPeriod::getMvccVersion);
			attributeGetterFunctions.put(
				"symptomId", SymptomPeriod::getSymptomId);
			attributeGetterFunctions.put(
				"companyId", SymptomPeriod::getCompanyId);
			attributeGetterFunctions.put("userId", SymptomPeriod::getUserId);
			attributeGetterFunctions.put(
				"createDate", SymptomPeriod::getCreateDate);
			attributeGetterFunctions.put(
				"subjectId", SymptomPeriod::getSubjectId);
			attributeGetterFunctions.put("name", SymptomPeriod::getName);
			attributeGetterFunctions.put(
				"startDate", SymptomPeriod::getStartDate);
			attributeGetterFunctions.put("endDate", SymptomPeriod::getEndDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SymptomPeriod, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SymptomPeriod, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<SymptomPeriod, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<SymptomPeriod, Long>)SymptomPeriod::setMvccVersion);
			attributeSetterBiConsumers.put(
				"symptomId",
				(BiConsumer<SymptomPeriod, Long>)SymptomPeriod::setSymptomId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SymptomPeriod, Long>)SymptomPeriod::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<SymptomPeriod, Long>)SymptomPeriod::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SymptomPeriod, Date>)SymptomPeriod::setCreateDate);
			attributeSetterBiConsumers.put(
				"subjectId",
				(BiConsumer<SymptomPeriod, Long>)SymptomPeriod::setSubjectId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<SymptomPeriod, String>)SymptomPeriod::setName);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<SymptomPeriod, Date>)SymptomPeriod::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<SymptomPeriod, Date>)SymptomPeriod::setEndDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getSymptomId() {
		return _symptomId;
	}

	@Override
	public void setSymptomId(long symptomId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_symptomId = symptomId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subjectId = subjectId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SymptomPeriod.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SymptomPeriod toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SymptomPeriod>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SymptomPeriodImpl symptomPeriodImpl = new SymptomPeriodImpl();

		symptomPeriodImpl.setMvccVersion(getMvccVersion());
		symptomPeriodImpl.setSymptomId(getSymptomId());
		symptomPeriodImpl.setCompanyId(getCompanyId());
		symptomPeriodImpl.setUserId(getUserId());
		symptomPeriodImpl.setCreateDate(getCreateDate());
		symptomPeriodImpl.setSubjectId(getSubjectId());
		symptomPeriodImpl.setName(getName());
		symptomPeriodImpl.setStartDate(getStartDate());
		symptomPeriodImpl.setEndDate(getEndDate());

		symptomPeriodImpl.resetOriginalValues();

		return symptomPeriodImpl;
	}

	@Override
	public SymptomPeriod cloneWithOriginalValues() {
		SymptomPeriodImpl symptomPeriodImpl = new SymptomPeriodImpl();

		symptomPeriodImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		symptomPeriodImpl.setSymptomId(
			this.<Long>getColumnOriginalValue("symptomId"));
		symptomPeriodImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		symptomPeriodImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		symptomPeriodImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		symptomPeriodImpl.setSubjectId(
			this.<Long>getColumnOriginalValue("subjectId"));
		symptomPeriodImpl.setName(this.<String>getColumnOriginalValue("name"));
		symptomPeriodImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		symptomPeriodImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));

		return symptomPeriodImpl;
	}

	@Override
	public int compareTo(SymptomPeriod symptomPeriod) {
		long primaryKey = symptomPeriod.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SymptomPeriod)) {
			return false;
		}

		SymptomPeriod symptomPeriod = (SymptomPeriod)object;

		long primaryKey = symptomPeriod.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SymptomPeriod> toCacheModel() {
		SymptomPeriodCacheModel symptomPeriodCacheModel =
			new SymptomPeriodCacheModel();

		symptomPeriodCacheModel.mvccVersion = getMvccVersion();

		symptomPeriodCacheModel.symptomId = getSymptomId();

		symptomPeriodCacheModel.companyId = getCompanyId();

		symptomPeriodCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			symptomPeriodCacheModel.createDate = createDate.getTime();
		}
		else {
			symptomPeriodCacheModel.createDate = Long.MIN_VALUE;
		}

		symptomPeriodCacheModel.subjectId = getSubjectId();

		symptomPeriodCacheModel.name = getName();

		String name = symptomPeriodCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			symptomPeriodCacheModel.name = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			symptomPeriodCacheModel.startDate = startDate.getTime();
		}
		else {
			symptomPeriodCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			symptomPeriodCacheModel.endDate = endDate.getTime();
		}
		else {
			symptomPeriodCacheModel.endDate = Long.MIN_VALUE;
		}

		return symptomPeriodCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SymptomPeriod, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SymptomPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SymptomPeriod, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SymptomPeriod)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SymptomPeriod>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SymptomPeriod.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _symptomId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private long _subjectId;
	private String _name;
	private Date _startDate;
	private Date _endDate;

	public <T> T getColumnValue(String columnName) {
		Function<SymptomPeriod, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SymptomPeriod)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("symptomId", _symptomId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("subjectId", _subjectId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("symptomId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("subjectId", 32L);

		columnBitmasks.put("name", 64L);

		columnBitmasks.put("startDate", 128L);

		columnBitmasks.put("endDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SymptomPeriod _escapedModel;

}