/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.account.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.account.model.Subject;
import com.tokogae.account.model.SubjectModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Subject service. Represents a row in the &quot;TOKOGAE_Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubjectModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SubjectImpl
 * @generated
 */
@JSON(strict = true)
public class SubjectModelImpl
	extends BaseModelImpl<Subject> implements SubjectModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject model instance should use the <code>Subject</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAE_Subject";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"subjectId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"displayName", Types.VARCHAR}, {"gender", Types.INTEGER},
		{"birthday", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("birthday", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAE_Subject (mvccVersion LONG default 0 not null,subjectId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,displayName VARCHAR(75) null,gender INTEGER,birthday DATE null)";

	public static final String TABLE_SQL_DROP = "drop table TOKOGAE_Subject";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subject.subjectId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAE_Subject.subjectId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBJECTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SubjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Subject.class;
	}

	@Override
	public String getModelClassName() {
		return Subject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Subject, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subject, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Subject)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Subject, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Subject, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Subject)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Subject, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Subject, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Subject, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Subject, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Subject, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", Subject::getMvccVersion);
			attributeGetterFunctions.put("subjectId", Subject::getSubjectId);
			attributeGetterFunctions.put("companyId", Subject::getCompanyId);
			attributeGetterFunctions.put("userId", Subject::getUserId);
			attributeGetterFunctions.put("createDate", Subject::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Subject::getModifiedDate);
			attributeGetterFunctions.put("firstName", Subject::getFirstName);
			attributeGetterFunctions.put("lastName", Subject::getLastName);
			attributeGetterFunctions.put(
				"displayName", Subject::getDisplayName);
			attributeGetterFunctions.put("gender", Subject::getGender);
			attributeGetterFunctions.put("birthday", Subject::getBirthday);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Subject, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Subject, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Subject, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<Subject, Long>)Subject::setMvccVersion);
			attributeSetterBiConsumers.put(
				"subjectId", (BiConsumer<Subject, Long>)Subject::setSubjectId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Subject, Long>)Subject::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Subject, Long>)Subject::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Subject, Date>)Subject::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Subject, Date>)Subject::setModifiedDate);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<Subject, String>)Subject::setFirstName);
			attributeSetterBiConsumers.put(
				"lastName", (BiConsumer<Subject, String>)Subject::setLastName);
			attributeSetterBiConsumers.put(
				"displayName",
				(BiConsumer<Subject, String>)Subject::setDisplayName);
			attributeSetterBiConsumers.put(
				"gender", (BiConsumer<Subject, Integer>)Subject::setGender);
			attributeSetterBiConsumers.put(
				"birthday", (BiConsumer<Subject, Date>)Subject::setBirthday);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subjectId = subjectId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return "";
		}
		else {
			return _displayName;
		}
	}

	@Override
	public void setDisplayName(String displayName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_displayName = displayName;
	}

	@JSON
	@Override
	public int getGender() {
		return _gender;
	}

	@Override
	public void setGender(int gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public Date getBirthday() {
		return _birthday;
	}

	@Override
	public void setBirthday(Date birthday) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthday = birthday;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Subject.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Subject toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Subject>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubjectImpl subjectImpl = new SubjectImpl();

		subjectImpl.setMvccVersion(getMvccVersion());
		subjectImpl.setSubjectId(getSubjectId());
		subjectImpl.setCompanyId(getCompanyId());
		subjectImpl.setUserId(getUserId());
		subjectImpl.setCreateDate(getCreateDate());
		subjectImpl.setModifiedDate(getModifiedDate());
		subjectImpl.setFirstName(getFirstName());
		subjectImpl.setLastName(getLastName());
		subjectImpl.setDisplayName(getDisplayName());
		subjectImpl.setGender(getGender());
		subjectImpl.setBirthday(getBirthday());

		subjectImpl.resetOriginalValues();

		return subjectImpl;
	}

	@Override
	public Subject cloneWithOriginalValues() {
		SubjectImpl subjectImpl = new SubjectImpl();

		subjectImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		subjectImpl.setSubjectId(
			this.<Long>getColumnOriginalValue("subjectId"));
		subjectImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		subjectImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		subjectImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		subjectImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		subjectImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		subjectImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		subjectImpl.setDisplayName(
			this.<String>getColumnOriginalValue("displayName"));
		subjectImpl.setGender(this.<Integer>getColumnOriginalValue("gender"));
		subjectImpl.setBirthday(this.<Date>getColumnOriginalValue("birthday"));

		return subjectImpl;
	}

	@Override
	public int compareTo(Subject subject) {
		long primaryKey = subject.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Subject)) {
			return false;
		}

		Subject subject = (Subject)object;

		long primaryKey = subject.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Subject> toCacheModel() {
		SubjectCacheModel subjectCacheModel = new SubjectCacheModel();

		subjectCacheModel.mvccVersion = getMvccVersion();

		subjectCacheModel.subjectId = getSubjectId();

		subjectCacheModel.companyId = getCompanyId();

		subjectCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			subjectCacheModel.createDate = createDate.getTime();
		}
		else {
			subjectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subjectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subjectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subjectCacheModel.firstName = getFirstName();

		String firstName = subjectCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			subjectCacheModel.firstName = null;
		}

		subjectCacheModel.lastName = getLastName();

		String lastName = subjectCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			subjectCacheModel.lastName = null;
		}

		subjectCacheModel.displayName = getDisplayName();

		String displayName = subjectCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			subjectCacheModel.displayName = null;
		}

		subjectCacheModel.gender = getGender();

		Date birthday = getBirthday();

		if (birthday != null) {
			subjectCacheModel.birthday = birthday.getTime();
		}
		else {
			subjectCacheModel.birthday = Long.MIN_VALUE;
		}

		return subjectCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Subject, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Subject, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subject, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Subject)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Subject>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Subject.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _subjectId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _displayName;
	private int _gender;
	private Date _birthday;

	public <T> T getColumnValue(String columnName) {
		Function<Subject, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Subject)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("subjectId", _subjectId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("displayName", _displayName);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("birthday", _birthday);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("subjectId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("firstName", 64L);

		columnBitmasks.put("lastName", 128L);

		columnBitmasks.put("displayName", 256L);

		columnBitmasks.put("gender", 512L);

		columnBitmasks.put("birthday", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Subject _escapedModel;

}