/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.account.model.impl;

import com.tokogae.account.model.Subject;
import com.tokogae.account.service.SubjectLocalServiceUtil;

/**
 * The extended model base implementation for the Subject service. Represents a row in the &quot;Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see SubjectImpl
 * @see Subject
 * @generated
 */
public abstract class SubjectBaseImpl
	extends SubjectModelImpl implements Subject {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject model instance should use the <code>Subject</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubjectLocalServiceUtil.addSubject(this);
		}
		else {
			SubjectLocalServiceUtil.updateSubject(this);
		}
	}

}