/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tokogae.data.model.Phrase;
import com.tokogae.data.model.PhraseModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Phrase service. Represents a row in the &quot;TOKOGAEData_Phrase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PhraseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhraseImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see PhraseImpl
 * @generated
 */
@JSON(strict = true)
public class PhraseModelImpl
	extends BaseModelImpl<Phrase> implements PhraseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phrase model instance should use the <code>Phrase</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAEData_Phrase";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"phraseId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"text_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("phraseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("text_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAEData_Phrase (mvccVersion LONG default 0 not null,phraseId LONG not null primary key,companyId LONG,text_ VARCHAR(250) null)";

	public static final String TABLE_SQL_DROP = "drop table TOKOGAEData_Phrase";

	public static final String ORDER_BY_JPQL = " ORDER BY phrase.phraseId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAEData_Phrase.phraseId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEXT_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHRASEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PhraseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _phraseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPhraseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _phraseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Phrase.class;
	}

	@Override
	public String getModelClassName() {
		return Phrase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Phrase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Phrase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Phrase, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Phrase)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Phrase, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Phrase, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Phrase)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Phrase, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Phrase, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Phrase, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Phrase, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Phrase, Object>>();

			attributeGetterFunctions.put("mvccVersion", Phrase::getMvccVersion);
			attributeGetterFunctions.put("phraseId", Phrase::getPhraseId);
			attributeGetterFunctions.put("companyId", Phrase::getCompanyId);
			attributeGetterFunctions.put("text", Phrase::getText);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Phrase, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Phrase, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Phrase, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<Phrase, Long>)Phrase::setMvccVersion);
			attributeSetterBiConsumers.put(
				"phraseId", (BiConsumer<Phrase, Long>)Phrase::setPhraseId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Phrase, Long>)Phrase::setCompanyId);
			attributeSetterBiConsumers.put(
				"text", (BiConsumer<Phrase, String>)Phrase::setText);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getPhraseId() {
		return _phraseId;
	}

	@Override
	public void setPhraseId(long phraseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phraseId = phraseId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public String getText() {
		if (_text == null) {
			return "";
		}
		else {
			return _text;
		}
	}

	@Override
	public void setText(String text) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_text = text;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalText() {
		return getColumnOriginalValue("text_");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Phrase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Phrase toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Phrase>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhraseImpl phraseImpl = new PhraseImpl();

		phraseImpl.setMvccVersion(getMvccVersion());
		phraseImpl.setPhraseId(getPhraseId());
		phraseImpl.setCompanyId(getCompanyId());
		phraseImpl.setText(getText());

		phraseImpl.resetOriginalValues();

		return phraseImpl;
	}

	@Override
	public Phrase cloneWithOriginalValues() {
		PhraseImpl phraseImpl = new PhraseImpl();

		phraseImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		phraseImpl.setPhraseId(this.<Long>getColumnOriginalValue("phraseId"));
		phraseImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		phraseImpl.setText(this.<String>getColumnOriginalValue("text_"));

		return phraseImpl;
	}

	@Override
	public int compareTo(Phrase phrase) {
		long primaryKey = phrase.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Phrase)) {
			return false;
		}

		Phrase phrase = (Phrase)object;

		long primaryKey = phrase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Phrase> toCacheModel() {
		PhraseCacheModel phraseCacheModel = new PhraseCacheModel();

		phraseCacheModel.mvccVersion = getMvccVersion();

		phraseCacheModel.phraseId = getPhraseId();

		phraseCacheModel.companyId = getCompanyId();

		phraseCacheModel.text = getText();

		String text = phraseCacheModel.text;

		if ((text != null) && (text.length() == 0)) {
			phraseCacheModel.text = null;
		}

		return phraseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Phrase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Phrase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Phrase, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Phrase)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Phrase>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Phrase.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _phraseId;
	private long _companyId;
	private String _text;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Phrase, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Phrase)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("phraseId", _phraseId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("text_", _text);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("text_", "text");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("phraseId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("text_", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Phrase _escapedModel;

}