/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import com.tokogae.data.model.PhraseUsage;
import com.tokogae.data.model.PhraseUsageModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PhraseUsage service. Represents a row in the &quot;TOKOGAEData_PhraseUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PhraseUsageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhraseUsageImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see PhraseUsageImpl
 * @generated
 */
@JSON(strict = true)
public class PhraseUsageModelImpl
	extends BaseModelImpl<PhraseUsage> implements PhraseUsageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phrase usage model instance should use the <code>PhraseUsage</code> interface instead.
	 */
	public static final String TABLE_NAME = "TOKOGAEData_PhraseUsage";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"phraseUsageId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"phraseId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("phraseUsageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("phraseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TOKOGAEData_PhraseUsage (mvccVersion LONG default 0 not null,phraseUsageId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,phraseId LONG,classNameId LONG,classPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table TOKOGAEData_PhraseUsage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY phraseUsage.phraseUsageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TOKOGAEData_PhraseUsage.phraseUsageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHRASEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHRASEUSAGEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PhraseUsageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _phraseUsageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPhraseUsageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _phraseUsageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhraseUsage.class;
	}

	@Override
	public String getModelClassName() {
		return PhraseUsage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PhraseUsage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PhraseUsage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhraseUsage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PhraseUsage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PhraseUsage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PhraseUsage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PhraseUsage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PhraseUsage, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PhraseUsage, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PhraseUsage, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PhraseUsage, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<PhraseUsage, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PhraseUsage::getMvccVersion);
			attributeGetterFunctions.put(
				"phraseUsageId", PhraseUsage::getPhraseUsageId);
			attributeGetterFunctions.put(
				"companyId", PhraseUsage::getCompanyId);
			attributeGetterFunctions.put("userId", PhraseUsage::getUserId);
			attributeGetterFunctions.put(
				"createDate", PhraseUsage::getCreateDate);
			attributeGetterFunctions.put("phraseId", PhraseUsage::getPhraseId);
			attributeGetterFunctions.put(
				"classNameId", PhraseUsage::getClassNameId);
			attributeGetterFunctions.put("classPK", PhraseUsage::getClassPK);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PhraseUsage, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PhraseUsage, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PhraseUsage, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setMvccVersion);
			attributeSetterBiConsumers.put(
				"phraseUsageId",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setPhraseUsageId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PhraseUsage, Date>)PhraseUsage::setCreateDate);
			attributeSetterBiConsumers.put(
				"phraseId",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setPhraseId);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<PhraseUsage, Long>)PhraseUsage::setClassPK);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getPhraseUsageId() {
		return _phraseUsageId;
	}

	@Override
	public void setPhraseUsageId(long phraseUsageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phraseUsageId = phraseUsageId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getPhraseId() {
		return _phraseId;
	}

	@Override
	public void setPhraseId(long phraseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phraseId = phraseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPhraseId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("phraseId"));
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PhraseUsage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhraseUsage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PhraseUsage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhraseUsageImpl phraseUsageImpl = new PhraseUsageImpl();

		phraseUsageImpl.setMvccVersion(getMvccVersion());
		phraseUsageImpl.setPhraseUsageId(getPhraseUsageId());
		phraseUsageImpl.setCompanyId(getCompanyId());
		phraseUsageImpl.setUserId(getUserId());
		phraseUsageImpl.setCreateDate(getCreateDate());
		phraseUsageImpl.setPhraseId(getPhraseId());
		phraseUsageImpl.setClassNameId(getClassNameId());
		phraseUsageImpl.setClassPK(getClassPK());

		phraseUsageImpl.resetOriginalValues();

		return phraseUsageImpl;
	}

	@Override
	public PhraseUsage cloneWithOriginalValues() {
		PhraseUsageImpl phraseUsageImpl = new PhraseUsageImpl();

		phraseUsageImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		phraseUsageImpl.setPhraseUsageId(
			this.<Long>getColumnOriginalValue("phraseUsageId"));
		phraseUsageImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		phraseUsageImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		phraseUsageImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		phraseUsageImpl.setPhraseId(
			this.<Long>getColumnOriginalValue("phraseId"));
		phraseUsageImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		phraseUsageImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));

		return phraseUsageImpl;
	}

	@Override
	public int compareTo(PhraseUsage phraseUsage) {
		long primaryKey = phraseUsage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PhraseUsage)) {
			return false;
		}

		PhraseUsage phraseUsage = (PhraseUsage)object;

		long primaryKey = phraseUsage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PhraseUsage> toCacheModel() {
		PhraseUsageCacheModel phraseUsageCacheModel =
			new PhraseUsageCacheModel();

		phraseUsageCacheModel.mvccVersion = getMvccVersion();

		phraseUsageCacheModel.phraseUsageId = getPhraseUsageId();

		phraseUsageCacheModel.companyId = getCompanyId();

		phraseUsageCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			phraseUsageCacheModel.createDate = createDate.getTime();
		}
		else {
			phraseUsageCacheModel.createDate = Long.MIN_VALUE;
		}

		phraseUsageCacheModel.phraseId = getPhraseId();

		phraseUsageCacheModel.classNameId = getClassNameId();

		phraseUsageCacheModel.classPK = getClassPK();

		return phraseUsageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PhraseUsage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PhraseUsage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhraseUsage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PhraseUsage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PhraseUsage>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PhraseUsage.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _phraseUsageId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private long _phraseId;
	private long _classNameId;
	private long _classPK;

	public <T> T getColumnValue(String columnName) {
		Function<PhraseUsage, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PhraseUsage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("phraseUsageId", _phraseUsageId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("phraseId", _phraseId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("phraseUsageId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("phraseId", 32L);

		columnBitmasks.put("classNameId", 64L);

		columnBitmasks.put("classPK", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PhraseUsage _escapedModel;

}