/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model.impl;

import com.tokogae.data.model.PhraseUsage;
import com.tokogae.data.service.PhraseUsageLocalServiceUtil;

/**
 * The extended model base implementation for the PhraseUsage service. Represents a row in the &quot;TOKOGAEData_PhraseUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhraseUsageImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see PhraseUsageImpl
 * @see PhraseUsage
 * @generated
 */
public abstract class PhraseUsageBaseImpl
	extends PhraseUsageModelImpl implements PhraseUsage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phrase usage model instance should use the <code>PhraseUsage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PhraseUsageLocalServiceUtil.addPhraseUsage(this);
		}
		else {
			PhraseUsageLocalServiceUtil.updatePhraseUsage(this);
		}
	}

}