/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.model.impl;

import com.tokogae.data.model.Phrase;
import com.tokogae.data.service.PhraseLocalServiceUtil;

/**
 * The extended model base implementation for the Phrase service. Represents a row in the &quot;TOKOGAEData_Phrase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhraseImpl}.
 * </p>
 *
 * @author Amos Fong
 * @see PhraseImpl
 * @see Phrase
 * @generated
 */
public abstract class PhraseBaseImpl extends PhraseModelImpl implements Phrase {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phrase model instance should use the <code>Phrase</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PhraseLocalServiceUtil.addPhrase(this);
		}
		else {
			PhraseLocalServiceUtil.updatePhrase(this);
		}
	}

}