/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Exercise service. Represents a row in the &quot;TOKOGAEData_Exercise&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.event.model.impl.ExerciseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.event.model.impl.ExerciseImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see Exercise
 * @generated
 */
@ProviderType
public interface ExerciseModel
	extends BaseModel<Exercise>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exercise model instance should use the {@link Exercise} interface instead.
	 */

	/**
	 * Returns the primary key of this exercise.
	 *
	 * @return the primary key of this exercise
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exercise.
	 *
	 * @param primaryKey the primary key of this exercise
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this exercise.
	 *
	 * @return the mvcc version of this exercise
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this exercise.
	 *
	 * @param mvccVersion the mvcc version of this exercise
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the exercise ID of this exercise.
	 *
	 * @return the exercise ID of this exercise
	 */
	public long getExerciseId();

	/**
	 * Sets the exercise ID of this exercise.
	 *
	 * @param exerciseId the exercise ID of this exercise
	 */
	public void setExerciseId(long exerciseId);

	/**
	 * Returns the company ID of this exercise.
	 *
	 * @return the company ID of this exercise
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this exercise.
	 *
	 * @param companyId the company ID of this exercise
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this exercise.
	 *
	 * @return the user ID of this exercise
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this exercise.
	 *
	 * @param userId the user ID of this exercise
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this exercise.
	 *
	 * @return the user uuid of this exercise
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this exercise.
	 *
	 * @param userUuid the user uuid of this exercise
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this exercise.
	 *
	 * @return the create date of this exercise
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this exercise.
	 *
	 * @param createDate the create date of this exercise
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the occur day of this exercise.
	 *
	 * @return the occur day of this exercise
	 */
	public long getOccurDay();

	/**
	 * Sets the occur day of this exercise.
	 *
	 * @param occurDay the occur day of this exercise
	 */
	public void setOccurDay(long occurDay);

	/**
	 * Returns the occur day segment of this exercise.
	 *
	 * @return the occur day segment of this exercise
	 */
	public int getOccurDaySegment();

	/**
	 * Sets the occur day segment of this exercise.
	 *
	 * @param occurDaySegment the occur day segment of this exercise
	 */
	public void setOccurDaySegment(int occurDaySegment);

	/**
	 * Returns the occur time of this exercise.
	 *
	 * @return the occur time of this exercise
	 */
	public long getOccurTime();

	/**
	 * Sets the occur time of this exercise.
	 *
	 * @param occurTime the occur time of this exercise
	 */
	public void setOccurTime(long occurTime);

	/**
	 * Returns the name of this exercise.
	 *
	 * @return the name of this exercise
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this exercise.
	 *
	 * @param name the name of this exercise
	 */
	public void setName(String name);

	/**
	 * Returns the type of this exercise.
	 *
	 * @return the type of this exercise
	 */
	public int getType();

	/**
	 * Sets the type of this exercise.
	 *
	 * @param type the type of this exercise
	 */
	public void setType(int type);

	/**
	 * Returns the duration of this exercise.
	 *
	 * @return the duration of this exercise
	 */
	public int getDuration();

	/**
	 * Sets the duration of this exercise.
	 *
	 * @param duration the duration of this exercise
	 */
	public void setDuration(int duration);

	/**
	 * Returns the intensity level of this exercise.
	 *
	 * @return the intensity level of this exercise
	 */
	public int getIntensityLevel();

	/**
	 * Sets the intensity level of this exercise.
	 *
	 * @param intensityLevel the intensity level of this exercise
	 */
	public void setIntensityLevel(int intensityLevel);

	/**
	 * Returns the quantity of this exercise.
	 *
	 * @return the quantity of this exercise
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this exercise.
	 *
	 * @param quantity the quantity of this exercise
	 */
	public void setQuantity(int quantity);

	@Override
	public Exercise cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}