/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FoodItem service. Represents a row in the &quot;TOKOGAEData_FoodItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.event.model.impl.FoodItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.event.model.impl.FoodItemImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see FoodItem
 * @generated
 */
@ProviderType
public interface FoodItemModel
	extends BaseModel<FoodItem>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a food item model instance should use the {@link FoodItem} interface instead.
	 */

	/**
	 * Returns the primary key of this food item.
	 *
	 * @return the primary key of this food item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this food item.
	 *
	 * @param primaryKey the primary key of this food item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this food item.
	 *
	 * @return the mvcc version of this food item
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this food item.
	 *
	 * @param mvccVersion the mvcc version of this food item
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the food item ID of this food item.
	 *
	 * @return the food item ID of this food item
	 */
	public long getFoodItemId();

	/**
	 * Sets the food item ID of this food item.
	 *
	 * @param foodItemId the food item ID of this food item
	 */
	public void setFoodItemId(long foodItemId);

	/**
	 * Returns the company ID of this food item.
	 *
	 * @return the company ID of this food item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this food item.
	 *
	 * @param companyId the company ID of this food item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this food item.
	 *
	 * @return the user ID of this food item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this food item.
	 *
	 * @param userId the user ID of this food item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this food item.
	 *
	 * @return the user uuid of this food item
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this food item.
	 *
	 * @param userUuid the user uuid of this food item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this food item.
	 *
	 * @return the create date of this food item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this food item.
	 *
	 * @param createDate the create date of this food item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the subject ID of this food item.
	 *
	 * @return the subject ID of this food item
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this food item.
	 *
	 * @param subjectId the subject ID of this food item
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the occur day of this food item.
	 *
	 * @return the occur day of this food item
	 */
	public long getOccurDay();

	/**
	 * Sets the occur day of this food item.
	 *
	 * @param occurDay the occur day of this food item
	 */
	public void setOccurDay(long occurDay);

	/**
	 * Returns the occur day segment of this food item.
	 *
	 * @return the occur day segment of this food item
	 */
	public int getOccurDaySegment();

	/**
	 * Sets the occur day segment of this food item.
	 *
	 * @param occurDaySegment the occur day segment of this food item
	 */
	public void setOccurDaySegment(int occurDaySegment);

	/**
	 * Returns the occur time of this food item.
	 *
	 * @return the occur time of this food item
	 */
	public long getOccurTime();

	/**
	 * Sets the occur time of this food item.
	 *
	 * @param occurTime the occur time of this food item
	 */
	public void setOccurTime(long occurTime);

	/**
	 * Returns the name of this food item.
	 *
	 * @return the name of this food item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this food item.
	 *
	 * @param name the name of this food item
	 */
	public void setName(String name);

	/**
	 * Returns the location of origin of this food item.
	 *
	 * @return the location of origin of this food item
	 */
	@AutoEscape
	public String getLocationOfOrigin();

	/**
	 * Sets the location of origin of this food item.
	 *
	 * @param locationOfOrigin the location of origin of this food item
	 */
	public void setLocationOfOrigin(String locationOfOrigin);

	/**
	 * Returns the brand of this food item.
	 *
	 * @return the brand of this food item
	 */
	@AutoEscape
	public String getBrand();

	/**
	 * Sets the brand of this food item.
	 *
	 * @param brand the brand of this food item
	 */
	public void setBrand(String brand);

	/**
	 * Returns the quantity of this food item.
	 *
	 * @return the quantity of this food item
	 */
	public long getQuantity();

	/**
	 * Sets the quantity of this food item.
	 *
	 * @param quantity the quantity of this food item
	 */
	public void setQuantity(long quantity);

	/**
	 * Returns the quantity unit of this food item.
	 *
	 * @return the quantity unit of this food item
	 */
	@AutoEscape
	public String getQuantityUnit();

	/**
	 * Sets the quantity unit of this food item.
	 *
	 * @param quantityUnit the quantity unit of this food item
	 */
	public void setQuantityUnit(String quantityUnit);

	@Override
	public FoodItem cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}