/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Sleep service. Represents a row in the &quot;TOKOGAEData_Sleep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.event.model.impl.SleepModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.event.model.impl.SleepImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see Sleep
 * @generated
 */
@ProviderType
public interface SleepModel extends BaseModel<Sleep>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sleep model instance should use the {@link Sleep} interface instead.
	 */

	/**
	 * Returns the primary key of this sleep.
	 *
	 * @return the primary key of this sleep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sleep.
	 *
	 * @param primaryKey the primary key of this sleep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this sleep.
	 *
	 * @return the mvcc version of this sleep
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this sleep.
	 *
	 * @param mvccVersion the mvcc version of this sleep
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the sleep ID of this sleep.
	 *
	 * @return the sleep ID of this sleep
	 */
	public long getSleepId();

	/**
	 * Sets the sleep ID of this sleep.
	 *
	 * @param sleepId the sleep ID of this sleep
	 */
	public void setSleepId(long sleepId);

	/**
	 * Returns the company ID of this sleep.
	 *
	 * @return the company ID of this sleep
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sleep.
	 *
	 * @param companyId the company ID of this sleep
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sleep.
	 *
	 * @return the user ID of this sleep
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sleep.
	 *
	 * @param userId the user ID of this sleep
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sleep.
	 *
	 * @return the user uuid of this sleep
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sleep.
	 *
	 * @param userUuid the user uuid of this sleep
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this sleep.
	 *
	 * @return the create date of this sleep
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sleep.
	 *
	 * @param createDate the create date of this sleep
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the subject ID of this sleep.
	 *
	 * @return the subject ID of this sleep
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this sleep.
	 *
	 * @param subjectId the subject ID of this sleep
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the occur day base time of this sleep.
	 *
	 * @return the occur day base time of this sleep
	 */
	public long getOccurDayBaseTime();

	/**
	 * Sets the occur day base time of this sleep.
	 *
	 * @param occurDayBaseTime the occur day base time of this sleep
	 */
	public void setOccurDayBaseTime(long occurDayBaseTime);

	/**
	 * Returns the occur day native time of this sleep.
	 *
	 * @return the occur day native time of this sleep
	 */
	public long getOccurDayNativeTime();

	/**
	 * Sets the occur day native time of this sleep.
	 *
	 * @param occurDayNativeTime the occur day native time of this sleep
	 */
	public void setOccurDayNativeTime(long occurDayNativeTime);

	/**
	 * Returns the duration of this sleep.
	 *
	 * @return the duration of this sleep
	 */
	public long getDuration();

	/**
	 * Sets the duration of this sleep.
	 *
	 * @param duration the duration of this sleep
	 */
	public void setDuration(long duration);

	@Override
	public Sleep cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}