/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Symptom service. Represents a row in the &quot;TOKOGAEData_Symptom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.event.model.impl.SymptomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.event.model.impl.SymptomImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see Symptom
 * @generated
 */
@ProviderType
public interface SymptomModel
	extends BaseModel<Symptom>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a symptom model instance should use the {@link Symptom} interface instead.
	 */

	/**
	 * Returns the primary key of this symptom.
	 *
	 * @return the primary key of this symptom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this symptom.
	 *
	 * @param primaryKey the primary key of this symptom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this symptom.
	 *
	 * @return the mvcc version of this symptom
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this symptom.
	 *
	 * @param mvccVersion the mvcc version of this symptom
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the symptom ID of this symptom.
	 *
	 * @return the symptom ID of this symptom
	 */
	public long getSymptomId();

	/**
	 * Sets the symptom ID of this symptom.
	 *
	 * @param symptomId the symptom ID of this symptom
	 */
	public void setSymptomId(long symptomId);

	/**
	 * Returns the company ID of this symptom.
	 *
	 * @return the company ID of this symptom
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this symptom.
	 *
	 * @param companyId the company ID of this symptom
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this symptom.
	 *
	 * @return the user ID of this symptom
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this symptom.
	 *
	 * @param userId the user ID of this symptom
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this symptom.
	 *
	 * @return the user uuid of this symptom
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this symptom.
	 *
	 * @param userUuid the user uuid of this symptom
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this symptom.
	 *
	 * @return the create date of this symptom
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this symptom.
	 *
	 * @param createDate the create date of this symptom
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the subject ID of this symptom.
	 *
	 * @return the subject ID of this symptom
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this symptom.
	 *
	 * @param subjectId the subject ID of this symptom
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the occur day base time of this symptom.
	 *
	 * @return the occur day base time of this symptom
	 */
	public long getOccurDayBaseTime();

	/**
	 * Sets the occur day base time of this symptom.
	 *
	 * @param occurDayBaseTime the occur day base time of this symptom
	 */
	public void setOccurDayBaseTime(long occurDayBaseTime);

	/**
	 * Returns the occur day native time of this symptom.
	 *
	 * @return the occur day native time of this symptom
	 */
	public long getOccurDayNativeTime();

	/**
	 * Sets the occur day native time of this symptom.
	 *
	 * @param occurDayNativeTime the occur day native time of this symptom
	 */
	public void setOccurDayNativeTime(long occurDayNativeTime);

	/**
	 * Returns the duration of this symptom.
	 *
	 * @return the duration of this symptom
	 */
	public long getDuration();

	/**
	 * Sets the duration of this symptom.
	 *
	 * @param duration the duration of this symptom
	 */
	public void setDuration(long duration);

	/**
	 * Returns the name of this symptom.
	 *
	 * @return the name of this symptom
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this symptom.
	 *
	 * @param name the name of this symptom
	 */
	public void setName(String name);

	/**
	 * Returns the affected area of this symptom.
	 *
	 * @return the affected area of this symptom
	 */
	@AutoEscape
	public String getAffectedArea();

	/**
	 * Sets the affected area of this symptom.
	 *
	 * @param affectedArea the affected area of this symptom
	 */
	public void setAffectedArea(String affectedArea);

	/**
	 * Returns the intensity level of this symptom.
	 *
	 * @return the intensity level of this symptom
	 */
	public int getIntensityLevel();

	/**
	 * Sets the intensity level of this symptom.
	 *
	 * @param intensityLevel the intensity level of this symptom
	 */
	public void setIntensityLevel(int intensityLevel);

	@Override
	public Symptom cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}