/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.data.event.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SymptomPeriod service. Represents a row in the &quot;TOKOGAEData_SymptomPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.data.event.model.impl.SymptomPeriodModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.data.event.model.impl.SymptomPeriodImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see SymptomPeriod
 * @generated
 */
@ProviderType
public interface SymptomPeriodModel
	extends BaseModel<SymptomPeriod>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a symptom period model instance should use the {@link SymptomPeriod} interface instead.
	 */

	/**
	 * Returns the primary key of this symptom period.
	 *
	 * @return the primary key of this symptom period
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this symptom period.
	 *
	 * @param primaryKey the primary key of this symptom period
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this symptom period.
	 *
	 * @return the mvcc version of this symptom period
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this symptom period.
	 *
	 * @param mvccVersion the mvcc version of this symptom period
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the symptom ID of this symptom period.
	 *
	 * @return the symptom ID of this symptom period
	 */
	public long getSymptomId();

	/**
	 * Sets the symptom ID of this symptom period.
	 *
	 * @param symptomId the symptom ID of this symptom period
	 */
	public void setSymptomId(long symptomId);

	/**
	 * Returns the company ID of this symptom period.
	 *
	 * @return the company ID of this symptom period
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this symptom period.
	 *
	 * @param companyId the company ID of this symptom period
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this symptom period.
	 *
	 * @return the user ID of this symptom period
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this symptom period.
	 *
	 * @param userId the user ID of this symptom period
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this symptom period.
	 *
	 * @return the user uuid of this symptom period
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this symptom period.
	 *
	 * @param userUuid the user uuid of this symptom period
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this symptom period.
	 *
	 * @return the create date of this symptom period
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this symptom period.
	 *
	 * @param createDate the create date of this symptom period
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the subject ID of this symptom period.
	 *
	 * @return the subject ID of this symptom period
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this symptom period.
	 *
	 * @param subjectId the subject ID of this symptom period
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the name of this symptom period.
	 *
	 * @return the name of this symptom period
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this symptom period.
	 *
	 * @param name the name of this symptom period
	 */
	public void setName(String name);

	/**
	 * Returns the start date of this symptom period.
	 *
	 * @return the start date of this symptom period
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this symptom period.
	 *
	 * @param startDate the start date of this symptom period
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this symptom period.
	 *
	 * @return the end date of this symptom period
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this symptom period.
	 *
	 * @param endDate the end date of this symptom period
	 */
	public void setEndDate(Date endDate);

	@Override
	public SymptomPeriod cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}