/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package com.tokogae.account.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Subject service. Represents a row in the &quot;Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokogae.account.model.impl.SubjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokogae.account.model.impl.SubjectImpl</code>.
 * </p>
 *
 * @author Amos Fong
 * @see Subject
 * @generated
 */
@ProviderType
public interface SubjectModel
	extends BaseModel<Subject>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subject model instance should use the {@link Subject} interface instead.
	 */

	/**
	 * Returns the primary key of this subject.
	 *
	 * @return the primary key of this subject
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subject.
	 *
	 * @param primaryKey the primary key of this subject
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this subject.
	 *
	 * @return the mvcc version of this subject
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this subject.
	 *
	 * @param mvccVersion the mvcc version of this subject
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the subject ID of this subject.
	 *
	 * @return the subject ID of this subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this subject.
	 *
	 * @param subjectId the subject ID of this subject
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the company ID of this subject.
	 *
	 * @return the company ID of this subject
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this subject.
	 *
	 * @param companyId the company ID of this subject
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this subject.
	 *
	 * @return the user ID of this subject
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this subject.
	 *
	 * @param userId the user ID of this subject
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subject.
	 *
	 * @return the user uuid of this subject
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this subject.
	 *
	 * @param userUuid the user uuid of this subject
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this subject.
	 *
	 * @return the create date of this subject
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this subject.
	 *
	 * @param createDate the create date of this subject
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subject.
	 *
	 * @return the modified date of this subject
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subject.
	 *
	 * @param modifiedDate the modified date of this subject
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this subject.
	 *
	 * @return the first name of this subject
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this subject.
	 *
	 * @param firstName the first name of this subject
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this subject.
	 *
	 * @return the last name of this subject
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this subject.
	 *
	 * @param lastName the last name of this subject
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the display name of this subject.
	 *
	 * @return the display name of this subject
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this subject.
	 *
	 * @param displayName the display name of this subject
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the male of this subject.
	 *
	 * @return the male of this subject
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this subject is male.
	 *
	 * @return <code>true</code> if this subject is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this subject is male.
	 *
	 * @param male the male of this subject
	 */
	public void setMale(boolean male);

	/**
	 * Returns the birthday of this subject.
	 *
	 * @return the birthday of this subject
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this subject.
	 *
	 * @param birthday the birthday of this subject
	 */
	public void setBirthday(Date birthday);

	@Override
	public Subject cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}