dependencies {
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib.clay", version: "16.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.function", version: "5.5.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "4.0.0"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "163.0.0"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":tokogae-account:tokogae-account-api")
	compileOnly project(":tokogae-api")
	compileOnly project(":tokogae-data:tokogae-data-api")
	compileOnly project(":tokogae-data:tokogae-data-event:tokogae-data-event-api")
}